* MinEmacs

*MinEmacs* is a lightweight Emacs configuration framework, the keybinding is
highly inspired by Doom Emacs.

[[file:.github/minemacs.svg]]

** Why
I was using Doom Emacs, it is an excellent piece of software, which introduced
me to the Emacs world. However, I have a not very pleasant experience with it.
I'm using Emacs at the core of my workflow, I use it to write documents, write
programs in different programming languages, manage my emails, etc.

Therefore, I want a robust yet simple framework. Doom Emacs is a good choice,
And it is moving in a good direction, but recently, I'm experiencing a lot of
problems with it, sometimes I do a ~doom upgrade~, and just after, nothing works
properly, it happens only in my most busy days, causing additional stress to
manage. And to be honest, it is a bit too much for a configuration framework! It
implements a command line interface, a library with extra features,
configuration modules gluing a bunch of packages in an opinionated way, CI
commands, and recently a profile manager! Which adds extra complexity at each
layer.

** Install
Open a shell and run:

#+begin_src shell
git clone https://github.com/abougouffa/minemacs.git ~/.emacs.d && emacs
#+end_src

This will clone the repository, and launches Emacs, which, in the first run,
will install the required packages.

*** ⚠ Important note
Please note that I'm using a fresh Emacs (Emacs 30.0.50) built from source.

I'm trying to support at least Emacs 28.2, so [[file:modules/me-backports-29.el][I back port some of the new
functions/macros I use to Emacs 28]].

I've never tested this configuration with Emacs versions earlier than 28.2, and
I don't plan to do so!

** Customize
You can customize MinEmacs by adding these files under the =~/.minemacs.d=
directory:

1. Defining the list of enabled modules in =~/.minemacs.d/modules.el=.
2. Custom configuration in =~/.minemacs.d/config.el=.

This repository contains skeleton files for [[file:skel/modules.el][modules.el]] and [[file:skel/config.el][config.el]] (under
[[file:skel][skel/]]).

*** Environment variables
You can customize MinEmacs' behavior via some environment variables.

- =MINEMACS_DIR= or =MINEMACSDIR=: Path for MinEmacs user configuration directory,
  if not set, =~/.minemacs.d/= is used.
- =MINEMACS_MSG_LEVEL=: Change message log level, from 1 (only errors) to 4 (all
  messages).
- =MINEMACS_VERBOSE=: Be more verbose (useful for debugging).
- =MINEMACS_DEBUG=: Enable debugging at startup.
- =MINEMACS_ALPHA=: Set frame =background-alpha= to percentage (value from 0 to
  100).
- =MINEMACS_NOT_LAZY=: Load lazy packages immediately after loading Emacs.

** Troubleshooting
If you experienced an issue with MinEmacs, you can check the [[file:FAQ.org][FAQ]], check [[https://github.com/abougouffa/minemacs/issues][open
issues or open a new one]].
