* MinEmacs

This is a WIP for a personal lightweight Emacs configuration, it is highly
inspired by Doom Emacs.

[[https://github.com/abougouffa/minemacs][.github/minemacs.png]]

** Why
I was using Doom Emacs, it is an excellent piece of software, which introduced
me to the Emacs world. However, I have a not very pleasant experience with it.
I'm using Emacs at the core of my workflow, I use it to write documents, write
programs in different programming languages, manage my emails, etc.

Therefore, I want a robust yet simple framework. Doom Emacs is a good choice,
And it is moving in a good direction, but recently, I'm experiencing a lot of
problems with it, sometimes I do a ~doom upgrade~, and just after, nothing
works properly, it happens only in my most busy days, causing additional stress
to manage. And to be honest, it is a bit too much for a configuration framework!
It implements a command line interface, a library with extra features,
configuration modules gluing a bunch of packages in an opinionated way, CI
commands, and recently a profile manager! Which adds extra complexity at each
layer.

** Install
Open a shell and run:

#+begin_src shell
git clone https://github.com/abougouffa/minemacs.git ~/.emacs.d && emacs
#+end_src

This will clone the repo, and launches Emacs, which, in the first run, will
install the required packages.
