name: CI Windows

on:
  push:
    paths-ignore:
      - "cog.toml"
      - "**.md"
      - "skel/**"
      - "assets/**"
      - "docs/**"
      - "modules/obsolete/**"
      - ".gitignore/workflows/cocogitto.yaml"
      - ".gitignore/workflows/jekyll-gh-pages.yaml"
  pull_request:
  workflow_dispatch:
  # Run weekly
  schedule:
    - cron: "0 0 * * 0"

jobs:
  ci-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Emacs (Windows)
        run: |
          choco install emacs
      - name: Show Emacs version
        run: |
          emacs --version
      - name: Running MinEmacs with all modules
        run: |
          $env:HOME = "D:\a\minemacs\"
          $env:MINEMACS_LOAD_ALL_MODULES = "1"
          emacs --no-window-system --batch --script .github\workflows\scripts\ci-init.el
      - name: Running MinEmacs in always demand mode
        run: |
          echo "Loading Emacs with MINEMACS_ALWAYS_DEMAND"
          $env:HOME = "D:\a\minemacs\"
          $env:MINEMACS_ALWAYS_DEMAND = "1"
          emacs --no-window-system --batch --script .github\workflows\scripts\ci-init.el
      - name: Running MinEmacs in daemon mode
        run: |
          echo "Loading Emacs in daemon mode"
          $env:MINEMACS_LOAD_ALL_MODULES = "1"
          emacs --daemon --script .github\workflows\scripts\ci-init.el
          echo "Finished"
